[2024-04-07T18:50:54.197-0500] {processor.py:161} INFO - Started process (PID=55954) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:50:54.199-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:50:54.199-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:50:54.199-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:50:54.214-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:50:54.207-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:50:54.215-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:50:54.270-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.073 seconds
[2024-04-07T18:51:25.823-0500] {processor.py:161} INFO - Started process (PID=55995) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:51:25.824-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:51:25.824-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:51:25.824-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:51:25.839-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:51:25.832-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:51:25.840-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:51:25.891-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:51:56.752-0500] {processor.py:161} INFO - Started process (PID=56032) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:51:56.753-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:51:56.753-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:51:56.753-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:51:56.767-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:51:56.761-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:51:56.769-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:51:56.820-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:52:27.716-0500] {processor.py:161} INFO - Started process (PID=56071) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:52:27.718-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:52:27.718-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:52:27.718-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:52:27.732-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:52:27.726-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:52:27.734-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:52:27.784-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:52:58.661-0500] {processor.py:161} INFO - Started process (PID=56111) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:52:58.662-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:52:58.663-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:52:58.663-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:52:58.677-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:52:58.671-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:52:58.679-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:52:58.729-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.069 seconds
[2024-04-07T18:53:29.636-0500] {processor.py:161} INFO - Started process (PID=56148) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:53:29.637-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:53:29.637-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:53:29.637-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:53:29.652-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:53:29.645-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:53:29.654-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:53:29.704-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:54:00.611-0500] {processor.py:161} INFO - Started process (PID=56187) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:54:00.612-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:54:00.613-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:54:00.613-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:54:00.626-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:54:00.620-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:54:00.628-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:54:00.678-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:54:31.470-0500] {processor.py:161} INFO - Started process (PID=56227) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:54:31.471-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:54:31.472-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:54:31.472-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:54:31.486-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:54:31.480-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:54:31.488-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:54:31.538-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:55:02.383-0500] {processor.py:161} INFO - Started process (PID=56265) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:55:02.385-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:55:02.385-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:55:02.385-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:55:02.399-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:55:02.393-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:55:02.401-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:55:02.452-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:55:33.260-0500] {processor.py:161} INFO - Started process (PID=56303) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:55:33.261-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:55:33.261-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:55:33.261-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:55:33.276-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:55:33.269-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:55:33.278-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:55:33.328-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.069 seconds
[2024-04-07T18:56:04.099-0500] {processor.py:161} INFO - Started process (PID=56344) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:56:04.100-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:56:04.100-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:56:04.100-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:56:04.114-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:56:04.108-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:56:04.116-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:56:04.166-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:56:35.075-0500] {processor.py:161} INFO - Started process (PID=56385) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:56:35.076-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:56:35.077-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:56:35.077-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:56:35.092-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:56:35.085-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:56:35.094-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:56:35.149-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.075 seconds
[2024-04-07T18:57:06.112-0500] {processor.py:161} INFO - Started process (PID=56422) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:57:06.114-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:57:06.114-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:57:06.114-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:57:06.128-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:57:06.122-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:57:06.130-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:57:06.181-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.069 seconds
[2024-04-07T18:57:36.933-0500] {processor.py:161} INFO - Started process (PID=56460) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:57:36.934-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:57:36.935-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:57:36.935-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:57:36.950-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:57:36.944-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:57:36.952-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:57:37.003-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.070 seconds
[2024-04-07T18:58:07.726-0500] {processor.py:161} INFO - Started process (PID=56498) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:58:07.728-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:58:07.728-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:58:07.728-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:58:07.742-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:58:07.736-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:58:07.744-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:58:07.795-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.069 seconds
[2024-04-07T18:58:38.625-0500] {processor.py:161} INFO - Started process (PID=56539) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:58:38.627-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:58:38.627-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:58:38.627-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:58:38.641-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:58:38.635-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:58:38.643-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:58:38.696-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.071 seconds
[2024-04-07T18:59:09.330-0500] {processor.py:161} INFO - Started process (PID=56583) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:59:09.331-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:59:09.332-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:59:09.332-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:59:09.346-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:59:09.340-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:59:09.348-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:59:09.398-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
[2024-04-07T18:59:40.132-0500] {processor.py:161} INFO - Started process (PID=56621) to work on /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:59:40.134-0500] {processor.py:830} INFO - Processing file /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py for tasks to queue
[2024-04-07T18:59:40.134-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:59:40.134-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:59:40.148-0500] {logging_mixin.py:188} INFO - [2024-04-07T18:59:40.142-0500] {dagbag.py:350} ERROR - Failed to import: /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
Traceback (most recent call last):
  File "/Users/james/Desktop/projects/airflow-local/airflow_venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2024-04-07T18:59:40.150-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py
[2024-04-07T18:59:40.200-0500] {processor.py:183} INFO - Processing /Users/james/Desktop/projects/airflow-local/airflow_home/dags/basic_etl.py took 0.068 seconds
